version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=custom_materials
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./:/mnt/extra-addons/custom_materials
    command: odoo -c /etc/odoo/odoo.conf --test-enable -d custom_materials -i custom_materials --test-tags /custom_materials --log-level=test


volumes:
  odoo-db-data:
  odoo-web-data:
